# Generated by Django 5.2.4 on 2025-07-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('main_actor', models.CharField(max_length=50)),
                ('rating', models.PositiveIntegerField()),
                ('running_time', models.PositiveIntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
